use_frameworks!

platform :ios, '8.0'

target 'CHOPopoverLauncher_Example' do
  pod 'CHOPopoverLauncher', :path => '../'

  target 'CHOPopoverLauncher_Tests' do
    inherit! :search_paths
    
  end
end
